-- MNT Academy — local development seed.
--
-- Runs automatically on `supabase start` / `supabase db reset`.
-- LOCAL ONLY. Fictional fixtures; never run this against a hosted project.
--
-- Rewritten 2026-09-26: the old catalogue (programs/modules/labs),
-- enrollment, and uuid-keyed module_progress fixtures targeted tables that
-- 20260828160000_simplify_schema.sql dropped, so every fresh
-- `supabase db reset` aborted at seed time with
--   column "module_id" of relation "module_progress" does not exist.
-- Course content lives in portal/data.js; the four user1-4 entitlement demo
-- accounts went with the enrollment model they exercised.
--
-- The empty-string token columns on auth.users are required. GoTrue scans
-- them into non-nullable Go strings, so leaving them NULL makes every sign-in
-- fail with "Database error querying schema" — which looks like a config
-- problem and is not. Do not drop these columns from the insert.
--
-- Staging instructor passwords are generated fresh on every `supabase db
-- reset` and never written to this file. Look them up in the local admin
-- panel's "view credentials" action, or rotate them from the roster.

-- One DO block on purpose: the CLI sends seed.sql as a single pipelined
-- batch, so a table created by one statement is not visible to the next
-- ("relation ... does not exist"). Keep the generated passwords in variables.
do $$
declare
  v_hd_pw    text := encode(gen_random_bytes(12), 'base64');
  v_socan_pw text := encode(gen_random_bytes(12), 'base64');
begin
  -- Dedicated local staging instructors. These are fictional fixtures only;
  -- their bcrypt hashes are generated by Postgres crypt(), as Supabase Auth
  -- requires. They deliberately use the app's missionnext.example convention.
  insert into auth.users
    (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
     raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
     confirmation_token, recovery_token, email_change,
     email_change_token_new, email_change_token_current,
     phone_change, phone_change_token, reauthentication_token)
  values
    ('00000000-0000-0000-0000-000000000000',
     '55555555-5555-5555-5555-555555555555', 'authenticated', 'authenticated',
     '3184759261-hdinst@missionnext.example', crypt(v_hd_pw, gen_salt('bf')), now(),
     '{"provider":"email","providers":["email"]}', '{"full_name":"Help Desk Staging Instructor"}', now(), now(),
     '', '', '', '', '', '', '', ''),
    ('00000000-0000-0000-0000-000000000000',
     '66666666-6666-6666-6666-666666666666', 'authenticated', 'authenticated',
     '6291847350-socaninst@missionnext.example', crypt(v_socan_pw, gen_salt('bf')), now(),
     '{"provider":"email","providers":["email"]}', '{"full_name":"SOC Analyst Staging Instructor"}', now(), now(),
     '', '', '', '', '', '', '', '');

  insert into auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at)
  select u.id, u.id, u.id::text,
         json_build_object('sub', u.id::text, 'email', u.email)::jsonb,
         'email', now(), now()
  from auth.users u
  where u.email in ('3184759261-hdinst@missionnext.example', '6291847350-socaninst@missionnext.example');

  -- Active instructor identities have no learner enrollment. The dedicated
  -- `is_instructor` flag is a UI/identity signal; the assignment table below
  -- is the actual permission boundary for course dashboards and messages.
  insert into public.students (student_id, user_id, track_code, is_admin, is_instructor, is_enrolled)
  values
    ('3184759261-HDINST', '55555555-5555-5555-5555-555555555555', 'HDINST', false, true, true),
    ('6291847350-SOCANINST', '66666666-6666-6666-6666-666666666666', 'SOCANINST', false, true, true);

  insert into public.faculty_course_assignments (user_id, track_code, active)
  values
    ('55555555-5555-5555-5555-555555555555', 'HDESK', true),
    ('66666666-6666-6666-6666-666666666666', 'SOCAN', true);

  -- Mirror the generated passwords into the admin-only lookup table. Never
  -- seed these fixture values into a hosted project.
  insert into public.student_credentials (student_id, password)
  values ('3184759261-HDINST', v_hd_pw),
         ('6291847350-SOCANINST', v_socan_pw);
end;
$$;
