// supabase/functions/admin-provision/provisioning.ts
//
// Ports bin/provision-students.js's login-id generation, password
// generation, and per-account creation logic (generatePassword(),
// generateUniqueLoginId(), createAuthUser(), insertStudent()) so
// index.ts can call it once per account for both the create_user and
// create_cohort actions. Same generation rules as the CLI script, so
// accounts created through the admin panel are indistinguishable in shape
// from ones created by the site owner running the script by hand.
//
// Everything in this file assumes it is only ever called AFTER index.ts's
// admin check has already passed — it takes a Supabase client as a
// parameter rather than deciding for itself which client (caller-scoped
// vs service-role) is safe to use, and every call site in index.ts passes
// the service-role client. This file does no authorization of its own.

// Auto-injected by the Supabase platform on every deployed Edge Function
// (and by `supabase functions serve` locally) — see index.ts's header
// comment for why SUPABASE_SERVICE_ROLE_KEY is the one var that needs an
// explicit `supabase secrets set` rather than relying on that injection.
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// Matches the check constraint on public.students.track_code
// (supabase/migrations/20260828120000_students_admin.sql). ADMIN is valid
// for create_user (a lone instructor/admin account) but deliberately
// excluded from cohort batches by index.ts's separate COHORT_TRACK_CODES —
// "cohorts are for students," per the sprint plan.
export const TRACK_CODES = ['SOCAN', 'HDESK', 'AIENG', 'ELECT', 'ADMIN'];

// Same charset and length (20 chars) as bin/provision-students.js's
// generatePassword(). No comma in the charset: that script's generated
// passwords land in an unquoted, comma-delimited CSV roster file
// (bin/.roster-output/*.csv) — a comma in the password would corrupt that
// file format. Kept identical here even though this function's own
// response is JSON (not CSV), so a password generated here is
// interchangeable with one generated by the CLI script and safe if ever
// copied into the same kind of roster file.
const PASSWORD_CHARS =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:.<>?';
const PASSWORD_LENGTH = 20;

export function generatePassword(): string {
  const bytes = new Uint8Array(PASSWORD_LENGTH);
  crypto.getRandomValues(bytes);
  let password = '';
  for (let i = 0; i < PASSWORD_LENGTH; i++) {
    password += PASSWORD_CHARS[bytes[i] % PASSWORD_CHARS.length];
  }
  return password;
}

// Random 10-digit login-id number, e.g. "4957361987". The CLI script uses
// Node's crypto.randomInt(1_000_000_000, 10_000_000_000) for this; Deno's
// std crypto has no direct equivalent, and combining two Uint32 values by
// multiplication (buf[0] * 2**32 + buf[1]) would overflow
// Number.MAX_SAFE_INTEGER (2**53) and lose precision. Instead: pick a
// non-zero leading digit (1-9, so the id is never zero-padded — matching
// the CLI script's range, which also never produces a leading zero) and 9
// further random digits (0-9), each drawn independently from
// crypto.getRandomValues. Not perfectly uniform across the full 10-digit
// space the way randomInt is, but plenty uniform for a login-id
// discriminator that already gets a DB uniqueness check + retry below, and
// it stays entirely within safe-integer/string arithmetic.
function randomTenDigitString(): string {
  const digits = new Uint8Array(10);
  crypto.getRandomValues(digits);
  let result = String(1 + (digits[0] % 9)); // leading digit: 1-9
  for (let i = 1; i < 10; i++) {
    result += String(digits[i] % 10);
  }
  return result;
}

// Ports generateUniqueLoginId(): random 10-digit number + "-{TRACKCODE}"
// suffix, checked against public.students and retried on collision (up to
// 20 attempts, same cap as the CLI script). Uses the Supabase client
// directly instead of the CLI script's raw REST fetch, since the caller
// already has a client in hand — same table, same filter, same intent.
export async function generateUniqueLoginId(
  // deno-lint-ignore no-explicit-any
  serviceClient: any,
  trackCode: string,
  retryCount = 0,
): Promise<string> {
  if (retryCount >= 20) {
    throw new Error(
      `Failed to generate unique login ID after 20 attempts for track code ${trackCode}`,
    );
  }

  const loginId = `${randomTenDigitString()}-${trackCode}`;

  const { data, error } = await serviceClient
    .from('students')
    .select('student_id')
    .eq('student_id', loginId)
    .limit(1);

  if (error) {
    throw new Error(`Failed to check login ID uniqueness: ${error.message}`);
  }

  if (data && data.length > 0) {
    return generateUniqueLoginId(serviceClient, trackCode, retryCount + 1);
  }

  return loginId;
}

// Ports createAuthUser(): identical endpoint, headers, and body shape to
// bin/provision-students.js's version — POST {SUPABASE_URL}/auth/v1/admin/users
// with the service-role key as both `apikey` and `Authorization: Bearer`,
// and { email, password, email_confirm: true } as the body.
export async function createAuthUser(
  email: string,
  password: string,
): Promise<string> {
  const response = await fetch(`${SUPABASE_URL}/auth/v1/admin/users`, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_SERVICE_ROLE_KEY,
      Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ email, password, email_confirm: true }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Auth user creation failed: ${response.status} ${response.statusText} - ${errorText}`,
    );
  }

  const data = await response.json();
  return data.id as string; // user_id UUID
}

export interface ProvisionOptions {
  trackCode: string;
  cohortId: string | null;
  isEnrolled: boolean;
}

export interface ProvisionedAccount {
  student_id: string;
  password: string;
  track_code: string;
}

// Combines the CLI script's per-account steps (unique id -> password ->
// auth user -> students row insert) into one call, parameterized by
// cohort_id and is_enrolled per the sprint plan's design decision:
//   - create_user (ad hoc, single account): cohort_id null (unless the
//     caller assigns one), is_enrolled false — an unassigned/not-yet-
//     activated generated account, matching "unused" cleanup semantics.
//   - create_cohort (batch): cohort_id set to the new cohort, is_enrolled
//     true — batch-generated cohort students are active by design, and
//     setting is_enrolled true here lets the existing
//     stamp_enrollment_dates() trigger
//     (supabase/migrations/20260829110000_enrollment_dates.sql) stamp
//     enrollment_date automatically; no extra write needed in this file.
export async function provisionOneAccount(
  // deno-lint-ignore no-explicit-any
  serviceClient: any,
  { trackCode, cohortId, isEnrolled }: ProvisionOptions,
): Promise<ProvisionedAccount> {
  const studentId = await generateUniqueLoginId(serviceClient, trackCode);
  const password = generatePassword();
  // Matches bin/provision-students.js's email convention exactly — do not
  // invent a different scheme.
  const email = `${studentId.toLowerCase()}@missionnext.example`;

  const userId = await createAuthUser(email, password);

  const { error: insertError } = await serviceClient.from('students').insert({
    student_id: studentId,
    user_id: userId,
    track_code: trackCode,
    is_admin: trackCode === 'ADMIN',
    cohort_id: cohortId,
    is_enrolled: isEnrolled,
  });

  if (insertError) {
    // The auth user now exists with no matching students row. This
    // function does not attempt to delete the orphaned auth user here —
    // that is a separate failure mode with its own risk (deleting a user
    // that a retry might otherwise be able to attach a students row to
    // later) and out of scope for this pass. Surfacing it clearly in the
    // thrown message is what lets the caller's failure list show the
    // mismatch instead of silently losing it.
    throw new Error(
      `Auth user ${userId} created but students row insert failed: ${insertError.message}`,
    );
  }

  // Admin-only plaintext copy for the admin panel's "view credentials"
  // action (20260901130100_student_credentials.sql) — see that migration's
  // header for why this exists alongside Supabase Auth's own hash.
  // Deliberately non-fatal: the students row above is already fully valid,
  // and the caller still gets this password back in the return value below
  // (today's one-time-reveal panel) even if this insert happens to fail.
  const { error: credentialsError } = await serviceClient
    .from('student_credentials')
    .insert({ student_id: studentId, password });
  if (credentialsError) {
    console.error(
      `student_credentials insert failed for ${studentId}: ${credentialsError.message}`,
    );
  }

  return { student_id: studentId, password, track_code: trackCode };
}
