(function(){
  function CloudShell({lab,user='Learner',cloudIncidentEngine,onCommand,onAction,onStateRestored}){
    const engine=cloudIncidentEngine, key=`mission_next_cloud_v1:${lab.id}:${user}`;
    const [mode,setMode]=React.useState('bash'),[line,setLine]=React.useState(''),[script,setScript]=React.useState('#!/usr/bin/env bash\n# Simulated recovery script\n'),[output,setOutput]=React.useState('SIMULATION ONLY — fictional cloud state in this browser. No Azure account is contacted.\n'),[error,setError]=React.useState(false);
    React.useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.state)engine?.restore(saved.state);if(saved?.script)setScript(saved.script);if(saved?.output)setOutput(saved.output);}catch(_){} onStateRestored?.({observed:{cloudIncident:engine?.snapshot()||{}}});},[]);
    function save(next=output){try{localStorage.setItem(key,JSON.stringify({state:engine?.snapshot(),script,output:next}));}catch(_){}}
    function run(){if(!engine||!line.trim())return;const result=engine.runCommand(line);const next=output+`\n${mode==='bash'?'cloud$':'PS /home/analyst>'} ${line}\n`+(result.stdout||result.stderr||'');setOutput(next);setError(result.exitCode!==0);save(next);onCommand?.(line,result,{cwd:'/home/analyst',user});setLine('');}
    function runScript(){const result=engine.runScript(script);const next=output+'\ncloud$ ./rebuild.sh\n'+(result.stdout||'')+(result.stderr||'');setOutput(next);setError(result.exitCode!==0);save(next);onAction?.('./rebuild.sh',result);}
    const s={root:{height:'100%',minHeight:520,display:'flex',flexDirection:'column',gap:8,padding:10,borderRadius:6,background:'#0b1220',color:'#e2e8f0',fontFamily:'Inter,system-ui,sans-serif'},banner:{padding:8,border:'1px solid #375a7f',background:'#10233d',borderRadius:5,fontSize:11,color:'#bfdbfe'},bar:{display:'flex',gap:8,alignItems:'center'},btn:{background:'#1e293b',border:'1px solid #475569',color:'#e2e8f0',borderRadius:4,padding:'6px 10px'},editor:{flex:1,minHeight:230,resize:'vertical',background:'#0d1117',color:'#d1fae5',border:'1px solid #334155',borderRadius:4,padding:10,font:'12px/1.6 Consolas,monospace'},terminal:{flex:1,minHeight:120,maxHeight:230,overflow:'auto',whiteSpace:'pre-wrap',background:'#050a14',border:'1px solid #1e293b',padding:10,font:'11px/1.5 Consolas,monospace'},row:{display:'flex',gap:7},input:{flex:1,minWidth:0,background:'#111827',border:'1px solid #334155',color:'#fff',padding:8,font:'12px Consolas,monospace'}};
    return <div style={s.root}><div style={s.banner}><b>SIMULATION ONLY</b> · Commands, script execution and files affect fictional training state stored in this browser.</div><div style={s.bar}><strong style={{marginRight:'auto'}}>Cloud Shell · /home/analyst</strong><button style={s.btn} onClick={()=>setMode(mode==='bash'?'powershell':'bash')}>{mode==='bash'?'Bash':'PowerShell'} ▾</button><button style={s.btn} onClick={()=>{const next=output+'\nSaved rebuild.sh in the virtual home directory.\n';setOutput(next);if(engine)engine.state.files['rebuild.sh']=script;save(next);}}>Save rebuild.sh</button><button style={s.btn} onClick={runScript}>Run Script</button></div><textarea aria-label="rebuild.sh editor" value={script} onChange={e=>setScript(e.target.value)} spellCheck={false} style={s.editor}/><div style={s.row}><input aria-label="Cloud Shell command" value={line} onChange={e=>setLine(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();run();}}} placeholder="Run KQL, az commands, or cat ir-ticket.txt" style={s.input}/><button style={s.btn} onClick={run}>Run</button></div><pre role="log" aria-live="polite" style={{...s.terminal,color:error?'#fecaca':'#e2e8f0'}}>{output}</pre></div>;
  }
  window.CloudShell=CloudShell;
})();
