(() => {
  'use strict';
  const STORAGE_KEY='mnt.m360.course.mock.v1';
  const SCHEMA_VERSION=1;
  const MIN_STORIES=4;
  const roadmap=[
    {week:'01',stage:'Direction',title:'Career Direction & Professional Brand',artifact:'Professional direction + brand + evidence'},
    {week:'02',stage:'Signal',title:'LinkedIn & Professional Presence',artifact:'Professional profile + public positioning'},
    {week:'03',stage:'Connection',title:'Networking & Professional Follow-Up',artifact:'Sanitized networking action + learning evidence'},
    {week:'04',stage:'Evidence',title:'Targeted Resume Development',artifact:'Targeted resume + evidence bullets'},
    {week:'05',stage:'Voice',title:'Interview Preparation & Practice',artifact:'STAR story bank + interview practice'},
    {week:'06',stage:'Proof',title:'Career Spotlight',artifact:'Career Spotlight + 30-day action plan'}
  ];
  function blankStory(){return{title:'',competency:'',context:'',action:'',result:'',interviewUse:''};}
  function blankDraft(){return{targetDirection:'',storyCandidate:'',starStories:Array.from({length:MIN_STORIES},blankStory),professionalIntroduction:'',technicalScenario:'',technicalReasoning:'',practiceWith:'',practiceQuestion:'',practiceObservation:'',interviewerQuestion1:'',interviewerQuestion2:'',interviewerQuestion3:'',improvementNext:'',improvementSupport:''};}
  function defaultState(){return{schemaVersion:SCHEMA_VERSION,updatedAt:null,weeks:{week1:{accepted:null},week2:{accepted:null},week3:{accepted:null},week4:{accepted:null},week5:{status:'draft',draft:blankDraft(),submitted:null,submittedAt:null,accepted:null,acceptedAt:null},week6:{status:'future'}}};}
  function safeParse(raw){try{return raw?JSON.parse(raw):null;}catch(_){return null;}}
  function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
  function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
  function normalizeStory(s){return{...blankStory(),...(s&&typeof s==='object'?s:{})};}
  function normalizeState(candidate){const base=defaultState();if(!candidate||typeof candidate!=='object')return base;const weeks=candidate.weeks||{},w5=weeks.week5||{},draft={...base.weeks.week5.draft,...(w5.draft||{})};draft.starStories=Array.isArray(draft.starStories)?draft.starStories.map(normalizeStory):[];while(draft.starStories.length<MIN_STORIES)draft.starStories.push(blankStory());return{...base,...candidate,schemaVersion:SCHEMA_VERSION,weeks:{...base.weeks,...weeks,week1:{...base.weeks.week1,...(weeks.week1||{})},week2:{...base.weeks.week2,...(weeks.week2||{})},week3:{...base.weeks.week3,...(weeks.week3||{})},week4:{...base.weeks.week4,...(weeks.week4||{})},week5:{...base.weeks.week5,...w5,draft,submitted:w5.submitted&&typeof w5.submitted==='object'?w5.submitted:null,accepted:w5.accepted&&typeof w5.accepted==='object'?w5.accepted:null}}};}
  let state=normalizeState(safeParse(localStorage.getItem(STORAGE_KEY)));
  const w5=()=>state.weeks.week5;
  const accepted=n=>state.weeks[`week${n}`]&&state.weeks[`week${n}`].accepted?state.weeks[`week${n}`].accepted:null;
  function renderStories(){const el=document.getElementById('starStories');el.innerHTML=w5().draft.starStories.map((s,i)=>`<article class="star-story"><div class="star-story-head"><strong>STAR story ${i+1}</strong><span>${i<MIN_STORIES?'Required':'Optional'}</span></div><div class="story-grid"><div class="field"><label>Story title</label><input data-m360 data-story-field="title" data-story-index="${i}" value="${esc(s.title)}" /></div><div class="field"><label>Competency demonstrated</label><input data-m360 data-story-field="competency" data-story-index="${i}" value="${esc(s.competency)}" /></div></div><div class="field"><label>Situation / task / context</label><textarea data-m360 data-story-field="context" data-story-index="${i}">${esc(s.context)}</textarea></div><div class="field"><label>Action you took</label><textarea data-m360 data-story-field="action" data-story-index="${i}">${esc(s.action)}</textarea></div><div class="field"><label>Result, learning, or outcome</label><textarea data-m360 data-story-field="result" data-story-index="${i}">${esc(s.result)}</textarea></div><div class="field"><label>Where could this story be useful in an interview?</label><textarea data-m360 data-story-field="interviewUse" data-story-index="${i}">${esc(s.interviewUse)}</textarea></div></article>`).join('');bindStoryInputs();}
  renderStories();
  function staticFields(){return Array.from(document.querySelectorAll('[data-m360]:not([data-story-field])'));}
  function syncStory(input){const i=Number(input.dataset.storyIndex),k=input.dataset.storyField;if(Number.isInteger(i)&&k&&w5().draft.starStories[i])w5().draft.starStories[i][k]=input.value.trim();}
  function bindStoryInputs(){document.querySelectorAll('[data-story-field]').forEach(input=>input.addEventListener('input',()=>{syncStory(input);markDraft();save(false);renderAll();}));}
  function sync(){staticFields().forEach(f=>w5().draft[f.id]=f.value.trim());document.querySelectorAll('[data-story-field]').forEach(syncStory);}
  function load(){staticFields().forEach(f=>f.value=typeof w5().draft[f.id]==='string'?w5().draft[f.id]:'');}
  function markDraft(){if(w5().status!=='draft')w5().status='draft';}
  function save(show){state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(show){const el=document.getElementById('saveState');el.textContent='Saved locally at '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});el.classList.add('saved');}}
  function storyComplete(s){return['title','competency','context','action','result','interviewUse'].every(k=>s[k]&&String(s[k]).trim());}
  function missing(){const d=w5().draft,checks=[['Target direction',d.targetDirection],['Practice partner/process',d.practiceWith],['Practiced question',d.practiceQuestion],['Practice feedback/self-observation',d.practiceObservation],['Interviewer question 1',d.interviewerQuestion1],['Interviewer question 2',d.interviewerQuestion2],['Improvement next practice',d.improvementNext],['Improvement support',d.improvementSupport]];const out=checks.filter(([,v])=>!v||!String(v).trim()).map(([l])=>l);d.starStories.slice(0,MIN_STORIES).forEach((s,i)=>{if(!storyComplete(s))out.push(`STAR story ${i+1}`);});return out;}
  function readyCount(){return[1,2,3,4,5,6].filter(n=>Boolean(accepted(n))).length;}
  function status(){const w=w5();if(w.status==='submitted')return'Submitted';if(w.status==='needs_revision')return'Needs Revision';if(w.status==='accepted')return'Meets Standard';if(w.accepted)return'Draft in progress';return'Draft';}
  function safeW3(w){return w?(w.showcaseInsight||w.reflectionLearned||''):'';}
  function renderCarry(){[1,2,3,4].forEach(n=>{const el=document.getElementById(`journeyWeek${n}`);if(el)el.classList.toggle('ready',Boolean(accepted(n)));});const title=document.getElementById('carryForwardTitle'),text=document.getElementById('carryForwardText'),details=document.getElementById('carryForwardDetails');const w1=accepted(1),w2=accepted(2),w3=accepted(3),w4=accepted(4);if(!w1&&!w2&&!w3&&!w4){title.textContent='No reviewer-approved prior artifacts are available yet.';text.textContent='Week 5 only reuses accepted evidence; mutable drafts are not carry-forward sources.';details.hidden=true;return;}title.textContent='Reviewer-approved evidence is available for interview preparation.';text.textContent='Use accepted evidence to build stories. Week 5 creates a new artifact and never changes earlier accepted snapshots.';const rows=[];if(w1&&w1.brandStatement)rows.push(['Week 1 professional brand',w1.brandStatement]);if(w2&&w2.headline)rows.push(['Week 2 headline',w2.headline]);const insight=safeW3(w3);if(insight)rows.push(['Week 3 sanitized insight',insight]);if(w4){if(w4.targetRole)rows.push(['Week 4 target',w4.targetRole]);const bullets=(w4.evidenceBullets||[]).filter(b=>b&&b.revised).slice(0,3).map(b=>b.revised).join(' | ');if(bullets)rows.push(['Week 4 evidence bullets',bullets]);if(w4.targetingNote)rows.push(['Week 4 targeting note',w4.targetingNote]);}details.innerHTML=rows.map(([l,v])=>`<div class="carry-row"><strong>${esc(l)}</strong><span>${esc(v)}</span></div>`).join('');details.hidden=false;if(!w5().draft.targetDirection){w5().draft.targetDirection=(w4&&w4.targetRole)||(w2&&w2.targetDirection)||(w1&&w1.direction)||'';const f=document.getElementById('targetDirection');if(f)f.value=w5().draft.targetDirection;}}
  function source(){const w=w5();return w.accepted||(w.status==='submitted'&&w.submitted)||w.draft;}
  function storyPreview(s){return(s.starStories||[]).filter(x=>x&&x.title&&x.competency).slice(0,4).map((x,i)=>`${i+1}. ${x.title} — ${x.competency}`).join('\n')||'Build at least four complete STAR stories in Practice It.';}
  function renderProof(){const w=w5(),s=source(),rows=[['Target direction',s.targetDirection||'Add your interview target direction.'],['STAR story bank',storyPreview(s)],['Practice evidence',s.practiceObservation||'Practice one answer and capture feedback or self-observation.'],['Interviewer questions',[s.interviewerQuestion1,s.interviewerQuestion2,s.interviewerQuestion3].filter(Boolean).join('\n')||'Add at least two thoughtful questions.'],['Improvement plan',[s.improvementNext,s.improvementSupport].filter(Boolean).join(' · ')||'Name what you will practice next and what support would help.']];if(s.professionalIntroduction&&s.professionalIntroduction.trim())rows.push(['Professional introduction (optional)',s.professionalIntroduction]);document.getElementById('week5ProofPreview').innerHTML=rows.map(([l,v])=>`<div class="portfolio-row"><div class="portfolio-key">${esc(l)}</div><div class="portfolio-value preserve-lines">${esc(v)}</div></div>`).join('');const b=document.getElementById('week5ArtifactStatus');b.textContent=w.accepted?'Portfolio Ready':w.status==='submitted'?'Submitted · not yet accepted':w.status==='needs_revision'?'Needs Revision':'DRAFT — NOT YET ACCEPTED';b.className='status-badge '+(w.accepted?'accepted':w.status==='submitted'?'submitted':w.status==='needs_revision'?'needs-revision':'draft');}
  function renderReview(){const l=document.getElementById('reviewStatusLabel'),t=document.getElementById('reviewStatusText'),w=w5();if(w.status==='submitted'){l.textContent='Submitted';t.textContent='The Week 5 interview-preparation snapshot is awaiting reviewer evaluation.';}else if(w.status==='needs_revision'){l.textContent='Needs Revision';t.textContent='Revise required stories or practice evidence and submit a new revision. Any prior accepted artifact remains preserved.';}else if(w.status==='accepted'){l.textContent='Meets Standard';t.textContent='Reviewer approval is complete. The accepted Week 5 evidence is Portfolio Ready and available for Week 6.';}else if(w.accepted){l.textContent='Draft in progress';t.textContent='You are editing a new draft. The prior accepted Week 5 artifact remains Portfolio Ready.';}else{l.textContent='Draft';t.textContent='Draft work has not been submitted for review.';}}
  function renderProgress(){const c=readyCount();document.getElementById('journeyProgress').textContent=`${c} of 6 artifacts portfolio ready`;document.getElementById('sidebarPortfolioCount').textContent=`${c} / 6`;document.getElementById('sidebarProgressBar').style.width=`${Math.round(c/6*100)}%`;document.getElementById('sidebarPriorStatus').textContent=`${[1,2,3,4].filter(n=>Boolean(accepted(n))).length} ready`;document.getElementById('sidebarWeek5Status').textContent=status();}
  function renderRoadmap(){document.getElementById('portfolioRoadmap').innerHTML=roadmap.map((item,i)=>{const r=Boolean(accepted(i+1));const label=i===4?(r?'Portfolio Ready':status()):r?'Portfolio Ready':i<4?'Not imported':'Future';return`<article class="roadmap-card ${r?'ready':''}"><span class="roadmap-state">${esc(label)}</span><div class="roadmap-week">WEEK ${item.week} · ${item.stage.toUpperCase()}</div><h4>${esc(item.title)}</h4><p>${esc(item.artifact)}</p></article>`;}).join('');}
  function renderAll(){renderCarry();renderReview();renderProof();renderProgress();renderRoadmap();}
  function validate(type,msg){const el=document.getElementById('validationMessage');el.textContent=msg;el.className=`validation-message show ${type}`;}
  function clear(){const el=document.getElementById('validationMessage');el.textContent='';el.className='validation-message';}
  staticFields().forEach(f=>f.addEventListener(f.tagName==='SELECT'?'change':'input',()=>{sync();markDraft();save(false);clear();renderAll();}));
  document.getElementById('addStoryBtn').addEventListener('click',()=>{sync();w5().draft.starStories.push(blankStory());renderStories();save(false);});
  document.getElementById('saveBtn').addEventListener('click',()=>{sync();markDraft();save(true);renderAll();validate('success','Draft saved. Nothing has been submitted for review.');});
  document.getElementById('submitReviewBtn').addEventListener('click',()=>{sync();const m=missing();if(m.length){validate('error','Complete the required Week 5 proof before submitting: '+m.join(', ')+'.');document.getElementById('practice').scrollIntoView({behavior:'smooth'});return;}w5().submitted=clone(w5().draft);w5().submittedAt=new Date().toISOString();w5().status='submitted';save(false);renderAll();validate('success','Week 5 submitted for review. Optional practice fields do not affect completion.');});
  document.getElementById('meetsStandardBtn').addEventListener('click',()=>{const w=w5();if(w.status!=='submitted'||!w.submitted){validate('error','Submit Week 5 before simulating reviewer approval.');return;}w.accepted=clone(w.submitted);w.acceptedAt=new Date().toISOString();w.status='accepted';save(false);renderAll();validate('success','Demo review: Meets Standard. Week 5 is Portfolio Ready and can feed Week 6.');});
  document.getElementById('needsRevisionBtn').addEventListener('click',()=>{const w=w5();if(w.status!=='submitted'||!w.submitted){validate('error','Submit Week 5 before simulating Needs Revision.');return;}w.status='needs_revision';save(false);renderAll();validate('error','Demo reviewer result: Needs Revision. Revise required work and resubmit.');});
  document.getElementById('resetReviewBtn').addEventListener('click',()=>{if(!confirm('Clear the Week 5 demo review state? The current draft will remain.'))return;const w=w5();w.status='draft';w.submitted=null;w.submittedAt=null;w.accepted=null;w.acceptedAt=null;save(false);renderAll();});
  load();renderAll();save(false);
})();
